on:
  schedule:
    - cron: "*/5 * * * *"
name: Stale Bot workflow
jobs:
  build:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: stale
        id: stale
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          operations-per-run: 300
          remove-stale-when-updated: true
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 7 days if no further activity occurs.
            If we missed this issue please reply to keep it active. You can also add the label "not stale" to keep this issue open!
            Thanks for being a part of the Nrwl community! 🙏
          exempt-issue-labels: |
            not stale,community,type:bug,type:docs
